### ISSUE TITLE
Services are not properly shutdown

### ISSUE THREAD

**Issue by NicolasMahe** [liteflow-labs/liteflow-js#36]
Services are not properly shutdown, the task listener seems to always listen and prevent the service to gracefully stop.
We should add a mechanism that stop the listener when the service receive the stop signal from docker.

**Comment by antho1404** [comment]
Do you have a way to reproduce that? I cannot reproduce.

**Comment by NicolasMahe** [comment]
look at the docker container logs of the service when it's being stopped

**Comment by antho1404** [comment]
Could you check that this has been fixed by https://github.com/liteflow-labs/liteflow-js/pull/82

**Comment by NicolasMahe** [comment]
The issue is not fixed.

This issue is related to the `@liteflow/service` lib, not the cli.
The problem is the library doesn't listen for SIGTERM and so never gracefully stop.
So when the cli stop a container, the cli wait 10sec (default of docker) before killing the container.

**Comment by antho1404** [comment]
With the new architecture of the services, this should be fixed by design. Could you confirm

**Comment by NicolasMahe** [comment]
This has been fixed by stopping the HTTP server of the service:
https://github.com/liteflow-labs/liteflow-js/blob/42a21b0ceef28e47ce3f0c38b508088f17aaa1b8/packages/service/src/index.ts#L115-L122
